services:
  koreanclub_frontend:
    container_name: koreanclub_frontend

    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_APP_NAME: Dibrugarh Korean Club
        NEXT_PUBLIC_API_URL: https://dibrugarhkoreanclub.shop/api/v1
        NEXT_PUBLIC_BACKEND_URL: https://dibrugarhkoreanclub.shop
        NEXT_PUBLIC_STORAGE_URL: https://dibrugarhkoreanclub.shop/storage

    restart: unless-stopped

    ports:
      - "3007:3000"
